# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    url: jdbc:mysql://${DATABASE_IP:192.168.7.112}:${DATABASE_PORT:3306}/${DATABASE_NAME:my_db}?characterEncoding=utf-8&allowMultiQueries=true&tinyInt1isBit=false
# mybatis配置
mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
