# ?????
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    # ??JDBC??????????????????JDBC???
    driver-class-name: dm.jdbc.driver.DmDriver
    # ??????????????
    username: SYSDBA
    # ???????????
    password: hxl0321731X
    # ????URL???jdbc:dm://<IP>:<??>/<????>?schema=<???schema>&????
    url: jdbc:dm://${DATABASE_IP:192.168.7.112}:${DATABASE_PORT:5236}/${DATABASE_NAME:DAMENG}?schema=fastmeeting&characterEncoding=utf-8&allowMultiQueries=true
    # Hikari ????????????MySQL????????
    hikari:
      minimum-idle: 15
      idle-timeout: 300000
      maximum-pool-size: 180
      auto-commit: true
      pool-name: hxlHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      # ???????????SELECT 1?????SELECT 1 FROM DUAL?
      connection-test-query: SELECT 1

# mybatis??
mybatis:
  #mapper????
  mapper-locations: classpath:mapper/*.xml
