# 数据源配置
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.kingbase8.Driver
    username: ${DB_USERNAME:admin}
    password: ${DB_PASSWORD:FsEntMeeting.com}
    url: jdbc:kingbase8://${DATABASE_IP:localhost}:${DATABASE_PORT:54321}/${DATABASE_NAME:fastmeeting}?clientEncoding=UTF8&currentSchema=public
# mybatis 配置
mybatis:
  #mapper 配置文件
  mapper-locations: classpath:mapper/*.xml